name = "GridLayoutBase"
uuid = "3955a311-db13-416c-9275-1d80ed98e5e9"
authors = ["Julius Krumbiegel"]
version = "0.3.3"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"

[compat]
GeometryBasics = "0.2"
Match = "^1"
Observables = "^0.2, 0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
