name = "GridLayoutBase"
uuid = "3955a311-db13-416c-9275-1d80ed98e5e9"
authors = ["Julius Krumbiegel"]
version = "0.1.0"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"

[compat]
Match = "^1"
Observables = "^0.2, 0.3"
GeometryTypes = "^0.7.10, 0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
